// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQHxVorYOyloIyZ9D2b_tEZMhiOntlpwI',
    appId: '1:624779079622:web:93c6d438eeda48374e8cc7',
    messagingSenderId: '624779079622',
    projectId: 'mambo-point',
    authDomain: 'mambo-point.firebaseapp.com',
    storageBucket: 'mambo-point.firebasestorage.app',
    measurementId: 'G-1MPQ2ZM3KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlekQPQnaJWkYhzO_1EHKI2FEs-CoSQC0',
    appId: '1:624779079622:android:447708dac8a2d81b4e8cc7',
    messagingSenderId: '624779079622',
    projectId: 'mambo-point',
    storageBucket: 'mambo-point.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoraRQhWiADOOHYhvFR0symF3NfOe11ro',
    appId: '1:624779079622:ios:7800a93c8888d82e4e8cc7',
    messagingSenderId: '624779079622',
    projectId: 'mambo-point',
    storageBucket: 'mambo-point.firebasestorage.app',
    iosBundleId: 'com.example.mambopoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoraRQhWiADOOHYhvFR0symF3NfOe11ro',
    appId: '1:624779079622:ios:7800a93c8888d82e4e8cc7',
    messagingSenderId: '624779079622',
    projectId: 'mambo-point',
    storageBucket: 'mambo-point.firebasestorage.app',
    iosBundleId: 'com.example.mambopoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQHxVorYOyloIyZ9D2b_tEZMhiOntlpwI',
    appId: '1:624779079622:web:204711951ee29ee34e8cc7',
    messagingSenderId: '624779079622',
    projectId: 'mambo-point',
    authDomain: 'mambo-point.firebaseapp.com',
    storageBucket: 'mambo-point.firebasestorage.app',
    measurementId: 'G-3KLQVVDS5Z',
  );
}
